services:
  - type: web
    name: tts-orchestrator
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn tts_orchestrator:app --host 0.0.0.0 --port $PORT"
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: GROQ_API_KEY
        fromSecret: true # You will set this in the Render dashboard
      - key: TELEPHONY_CODEC
        value: pcm_mulaw # or pcm_alaw
    disk:
      name: audio-cache
      mountPath: /app/public_audio
      sizeGB: 1
