services:
  # Add a free, managed Redis instance
  - type: pserv
    name: redis
    env: redis
    plan: free

  - type: web
    name: tts-orchestrator
    env: python
    plan: free
    buildCommand: "./render-build.sh"
    startCommand: "uvicorn tts_orchestrator:app --host 0.0.0.0 --port $PORT"
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: GROQ_API_KEY
        value: YOUR_API_KEY_HERE # Replace with your actual Groq API key in the Render dashboard
      - key: TELEPHONY_CODEC
        value: pcm_mulaw # or pcm_alaw

  # Add a new worker for the Relay Server
  - type: worker
    name: relay-server
    env: python
    buildCommand: "pip install -r requirements.txt" # Use the main requirements file
    startCommand: "python relay_server.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - fromService:
          type: web
          name: tts-orchestrator
          property: url
        key: TTS_ORCHESTRATOR_URL
      # You will need to set these secrets in the Render Dashboard
      # for the relay-server service.
      - key: SIGNALWIRE_PROJECT_ID
        sync: false
      - key: SIGNALWIRE_API_TOKEN
        sync: false
      - key: SIGNALWIRE_CONTEXT
        sync: false
      - fromService:
          type: pserv
          name: redis
          property: connectionString
        key: REDIS_URL
      - key: GROQ_API_KEY
        sync: false
