services:
  - type: web
    name: tts-orchestrator
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn tts_orchestrator:app --host 0.0.0.0 --port $PORT"
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: GROQ_API_KEY
        value: YOUR_API_KEY_HERE # Replace with your actual Groq API key in the Render dashboard
      - key: TELEPHONY_CODEC
        value: pcm_mulaw # or pcm_alaw
