services:
  # 1. Free Redis Instance for Celery
  - name: redis
    type: redis
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
        description: "Allow all connections"

  # 2. The main, unified Web Service
  - name: voice-agent-service
    type: web
    env: python
    plan: free
    buildCommand: "./render-build.sh"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    healthCheckPath: / # The root endpoint will serve as the health check
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis
          property: connectionString
      # The RENDER_EXTERNAL_URL is automatically provided by Render
      # and will be used by the application to know its own public address.
      - key: RENDER_EXTERNAL_URL
        sync: false
      # Add all your other secrets here in the Render Dashboard
      - key: GROQ_API_KEY
        sync: false
      - key: SIGNALWIRE_PROJECT_ID
        sync: false
      - key: SIGNALWIRE_API_TOKEN
        sync: false
      - key: SIGNALWIRE_CONTEXT
        sync: false
